services:
  mysql:
    image: mysql:8.4
    container_name: task_management_db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: guilherme
      MYSQL_DATABASE: TaskManagement

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
